#!/usr/bin/env python3
"""gen_scenarios.py — sinh C header `scenarios_gen.h` từ tools/scenarios.py.

Vì `umt_dash_sim` là executable C không thể import Python, bước build này đọc
tools/scenarios.py (NGUỒN DUY NHẤT, G1 T1.1) rồi xuất các mảng C tĩnh để main.c
của simulator dùng cho `--scenario <name>`. Giữ nguyên single-truth: sửa kịch
bản trong tools/scenarios.py là đủ.

Usage:
    python3 host_sim/gen_scenarios.py --scenarios tools/scenarios.py --out /tmp/scenarios_gen.h
"""
from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path


def load_scenarios(path: Path):
    spec = importlib.util.spec_from_file_location("scenarios", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def fmt_rows(rows) -> str:
    parts = []
    for row in rows:
        parts.append("        {" + ", ".join(f"{int(round(float(v)))}" for v in row) + "}")
    return ",\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--scenarios", required=True, help="Đường dẫn tools/scenarios.py")
    ap.add_argument("--out", required=True, help="Đường dẫn header C sinh ra")
    args = ap.parse_args()

    scenarios_path = Path(args.scenarios).resolve()
    out_path = Path(args.out).resolve()
    mod = load_scenarios(scenarios_path)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Auto-generated by host_sim/gen_scenarios.py from",
        " * tools/scenarios.py — DO NOT EDIT BY HAND (R10: sửa ở nguồn).",
        " * Định dạng: mỗi mốc = 6 uint16_t [d1..d6] (FRONT..RIGHT_REAR).",
        " */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "#define SIM_SCENARIO_COUNT %d" % len(SCENARIOS := mod.SCENARIO_NAMES),
        "",
    ]
    for name in mod.SCENARIO_NAMES:
        rows = list(mod.iter_scenario(name))
        lines.append(f"static const uint16_t k_sim_{name}[{len(rows)}][6] = {{")
        lines.append(fmt_rows(rows))
        lines.append("};")
        lines.append("")
    lines += [
        "typedef struct {",
        "    const char *name;",
        "    const uint16_t (*rows)[6];",
        "    int n;",
        "} sim_scenario_t;",
        "",
        "static const sim_scenario_t k_sim_scenarios[SIM_SCENARIO_COUNT] = {",
    ]
    for i, name in enumerate(mod.SCENARIO_NAMES):
        rows = list(mod.iter_scenario(name))
        lines.append(
            f'    {{"{name}", k_sim_{name}, {len(rows)}}},'
        )
    lines += [
        "};",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[gen_scenarios] {len(mod.SCENARIO_NAMES)} scenarios -> {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())