#!/usr/bin/env python3
"""gen_credentials.py — sinh `credentials.h` từ config/keys.json (gitignored).

R1: credential chỉ nằm ở config/keys.json hoặc file sinh từ nó.
File `credentials.h` KHÔNG được commit (đã ignore ở .gitignore).

Usage:
  python3 tools/guard/gen_credentials.py --out firmware/sensor-node/include/credentials.h
  python3 tools/guard/gen_credentials.py --check    # chỉ kiểm tra keys.json đủ field
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REQUIRED_FIELDS = [
    "COREIOT_BROKER",
    "COREIOT_PORT",
    "SENSOR_NODE_DEVICE_TOKEN",
    "WAVESHARE_SCREEN_DEVICE_TOKEN",
    "COREIOT_TELEMETRY_TOPIC",
    "WIFI_SSID",
    "WIFI_PASSWORD",
]

H_HEADER = (
    "/* AUTO-GENERATED by tools/guard/gen_credentials.py — DO NOT EDIT, DO NOT COMMIT. */\n"
    "#pragma once\n"
    "#define COREIOT_BROKER \"{broker}\"\n"
    "#define COREIOT_PORT {port}\n"
    "#define COREIOT_TELEMETRY_TOPIC \"{topic}\"\n"
    "#define SENSOR_NODE_DEVICE_TOKEN \"{sensor_token}\"\n"
    "#define WAVESHARE_SCREEN_DEVICE_TOKEN \"{screen_token}\"\n"
    "#define WIFI_SSID \"{wifi_ssid}\"\n"
    "#define WIFI_PASSWORD \"{wifi_password}\"\n"
)


def load_keys(keys_path: Path) -> dict:
    if not keys_path.exists():
        print(f"ERROR: {keys_path} not found. Run: cp config/keys.template.json config/keys.json", file=sys.stderr)
        sys.exit(2)
    data = json.loads(keys_path.read_text(encoding="utf-8"))
    missing = [k for k in REQUIRED_FIELDS if data.get(k, "").startswith("<")]
    if missing:
        print(f"ERROR: keys.json missing/placeholder fields: {', '.join(missing)}", file=sys.stderr)
        sys.exit(2)
    return data


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate credentials.h from config/keys.json")
    ap.add_argument("--keys", type=Path, default=Path("config/keys.json"))
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--check", action="store_true", help="validate only")
    args = ap.parse_args()

    data = load_keys(args.keys)

    if args.check:
        print("GEN-CREDENTIALS OK: keys.json valid (all fields filled).")
        return 0

    if args.out is None:
        print("ERROR: need --out <path> or --check", file=sys.stderr)
        return 2

    content = H_HEADER.format(
        broker=data["COREIOT_BROKER"],
        port=int(data["COREIOT_PORT"]),
        topic=data["COREIOT_TELEMETRY_TOPIC"],
        sensor_token=data["SENSOR_NODE_DEVICE_TOKEN"],
        screen_token=data["WAVESHARE_SCREEN_DEVICE_TOKEN"],
        wifi_ssid=data["WIFI_SSID"],
        wifi_password=data["WIFI_PASSWORD"],
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(content, encoding="utf-8")
    print(f"GEN-CREDENTIALS OK: wrote {args.out} ({len(content)} bytes). DO NOT COMMIT this file.")
    return 0


if __name__ == "__main__":
    sys.exit(main())